### ISSUE TITLE
Make Cases' machine account username a required attribute

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/ncs_navigator_configuration#15]
Currently, the Cases machine account username is not a required attribute.  This leads to unnecessary complexity in user lookup for Ops' machine account authority (see https://github.com/NUBIC/ncs_staff_portal/pull/2), which can no longer assume that `nil` criterion won't match anything:

``` ruby
module Aker::Authorities
  class MachineAccount
    def find_users(*criteria)
      case criteria.first
        when cases_machine_account_username; [cases_user]
        # ...
      end
    end

    def cases_machine_account_username
      # this could return nil, which would match in #find_users
      NcsNavigator.configuration.cases_machine_account_usernme
    end
  end
end
```

I don't know if this is a huge problem, but it is an unexpected behavior for `#find_users`, which shouldn't return `Aker::User` objects with nil usernames.  The behavior can be eliminated by requiring that the Cases machine account username be present, even if it not used.   (The password still does not need to be supplied.)

**Comment by hannahwhy** [comment]
This could also be fixed by inserting a `return [] if criteria.first.nil?` in `find_users`, but that seems like it's addressing the problem at the wrong level.

**Comment by rsutphin** [comment]
> I don't know if this is a huge problem, but it is an unexpected behavior for `#find_users`, which shouldn't return `Aker::User` objects with nil usernames. The behavior can be eliminated by requiring that the Cases machine account username be present, even if it not used. (The password still does not need to be supplied.)

I disagree in the general case — this is the consuming code's issue. It should ensure that it behaves properly for the full range of possible values from the configuration.

In this specific case, though, I don't see any harm in providing a default value in ncs_navigator_configuration for the Cases machine account's username. Then you can make it mandatory without increasing deployment complexity for the simple cases.

**Comment by hannahwhy** [comment]
> I don't see any harm in providing a default value in ncs_navigator_configuration for the Cases machine account's username. 

I'm not sure there's a sensible default.  `ncs_navigator_cases` is one option, but it's a default which is unsuitable for all of our deployments (and probably others' deployments as well).

This can be handled by the consumer pretty easily, though, so I'll handle that case there.

**Comment by rsutphin** [comment]
> I'm not sure there's a sensible default. ncs_navigator_cases is one option, but it's a default which is unsuitable for all of our deployments (and probably others' deployments as well).

I don't understand why `ncs_navigator_cases` is not a reasonable default. It makes sense for, say, a development environment. And similarly it makes sense for any environment where there's only one NCS Navigator instance. It doesn't make sense for NUBIC's more complex production deployment environment, but that's why it would be configurable.
