### ISSUE TITLE
Configuration Initialize fails on nil 'find' results

### ISSUE THREAD

**Issue by aaronzirbes** [NUARIG/ncs_navigator_configuration#5]
I've updated the following:

https://github.com/umn-enhs/ncs_staff_portal/blob/master/config/initializers/system_configuration.rb

so that missing config information prints out slightly more helpful information rather than a stack trace.

Use it if you wish.

**Comment by aaronzirbes** [comment]
...wrong project!

**Comment by rsutphin** [comment]
I added a staff portal [issue](https://code.bioinformatics.northwestern.edu/issues/issues/show/1685) to track this suggestion. Thanks.
